default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
gym(
scheme:"SSFree",

export_method:"ad-hoc",

output_directory:"./build",

export_xcargs:"-allowProvisioningUpdates",
)
  end
end
