on: [push]
name: swift_build
jobs:
  build:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: build
        run: |
          xcodebuild clean build -project SSFree.xcodeproj -scheme SSFree -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
         DEVELOPER_DIR: /Applications/Xcode_11.3.app
